\set ON_ERROR_STOP on

CREATE ROLE breev_schema_owner
  LOGIN
  PASSWORD '__SCHEMA_OWNER_PASSWORD__'
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOREPLICATION
  NOBYPASSRLS;

CREATE ROLE breev_runtime
  LOGIN
  PASSWORD '__RUNTIME_PASSWORD__'
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOREPLICATION
  NOBYPASSRLS;

CREATE DATABASE breev OWNER breev_schema_owner;

\connect breev

REVOKE ALL ON DATABASE breev FROM PUBLIC;
GRANT CONNECT ON DATABASE breev TO breev_runtime;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
ALTER SCHEMA public OWNER TO breev_schema_owner;
GRANT USAGE ON SCHEMA public TO breev_runtime;

ALTER DEFAULT PRIVILEGES FOR ROLE breev_schema_owner IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO breev_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE breev_schema_owner IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO breev_runtime;

ALTER ROLE breev_bootstrap NOLOGIN;
