/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as IntegrationRouteImport } from './routes/integration'
import { Route as ExternalIntegrationRouteImport } from './routes/external-integration'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as EcommerceRouteImport } from './routes/ecommerce'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClinicRouteImport } from './routes/clinic'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPurchaseOcrRouteImport } from './routes/api/purchase-ocr'
import { Route as ApiBreefAiRouteImport } from './routes/api/breef-ai'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationRoute = IntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternalIntegrationRoute = ExternalIntegrationRouteImport.update({
  id: '/external-integration',
  path: '/external-integration',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const EcommerceRoute = EcommerceRouteImport.update({
  id: '/ecommerce',
  path: '/ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicRoute = ClinicRouteImport.update({
  id: '/clinic',
  path: '/clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPurchaseOcrRoute = ApiPurchaseOcrRouteImport.update({
  id: '/api/purchase-ocr',
  path: '/api/purchase-ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBreefAiRoute = ApiBreefAiRouteImport.update({
  id: '/api/breef-ai',
  path: '/api/breef-ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/clinic': typeof ClinicRoute
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRoute
  '/ecommerce': typeof EcommerceRoute
  '/employees': typeof EmployeesRoute
  '/external-integration': typeof ExternalIntegrationRoute
  '/integration': typeof IntegrationRoute
  '/inventory': typeof InventoryRoute
  '/marketing': typeof MarketingRoute
  '/messages': typeof MessagesRoute
  '/patients': typeof PatientsRoute
  '/products': typeof ProductsRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/breef-ai': typeof ApiBreefAiRoute
  '/api/purchase-ocr': typeof ApiPurchaseOcrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/clinic': typeof ClinicRoute
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRoute
  '/ecommerce': typeof EcommerceRoute
  '/employees': typeof EmployeesRoute
  '/external-integration': typeof ExternalIntegrationRoute
  '/integration': typeof IntegrationRoute
  '/inventory': typeof InventoryRoute
  '/marketing': typeof MarketingRoute
  '/messages': typeof MessagesRoute
  '/patients': typeof PatientsRoute
  '/products': typeof ProductsRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/breef-ai': typeof ApiBreefAiRoute
  '/api/purchase-ocr': typeof ApiPurchaseOcrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/clinic': typeof ClinicRoute
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRoute
  '/ecommerce': typeof EcommerceRoute
  '/employees': typeof EmployeesRoute
  '/external-integration': typeof ExternalIntegrationRoute
  '/integration': typeof IntegrationRoute
  '/inventory': typeof InventoryRoute
  '/marketing': typeof MarketingRoute
  '/messages': typeof MessagesRoute
  '/patients': typeof PatientsRoute
  '/products': typeof ProductsRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/breef-ai': typeof ApiBreefAiRoute
  '/api/purchase-ocr': typeof ApiPurchaseOcrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/auth'
    | '/cart'
    | '/clinic'
    | '/dashboard'
    | '/delivery'
    | '/ecommerce'
    | '/employees'
    | '/external-integration'
    | '/integration'
    | '/inventory'
    | '/marketing'
    | '/messages'
    | '/patients'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/settings'
    | '/api/breef-ai'
    | '/api/purchase-ocr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/auth'
    | '/cart'
    | '/clinic'
    | '/dashboard'
    | '/delivery'
    | '/ecommerce'
    | '/employees'
    | '/external-integration'
    | '/integration'
    | '/inventory'
    | '/marketing'
    | '/messages'
    | '/patients'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/settings'
    | '/api/breef-ai'
    | '/api/purchase-ocr'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/auth'
    | '/cart'
    | '/clinic'
    | '/dashboard'
    | '/delivery'
    | '/ecommerce'
    | '/employees'
    | '/external-integration'
    | '/integration'
    | '/inventory'
    | '/marketing'
    | '/messages'
    | '/patients'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/settings'
    | '/api/breef-ai'
    | '/api/purchase-ocr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  ClinicRoute: typeof ClinicRoute
  DashboardRoute: typeof DashboardRoute
  DeliveryRoute: typeof DeliveryRoute
  EcommerceRoute: typeof EcommerceRoute
  EmployeesRoute: typeof EmployeesRoute
  ExternalIntegrationRoute: typeof ExternalIntegrationRoute
  IntegrationRoute: typeof IntegrationRoute
  InventoryRoute: typeof InventoryRoute
  MarketingRoute: typeof MarketingRoute
  MessagesRoute: typeof MessagesRoute
  PatientsRoute: typeof PatientsRoute
  ProductsRoute: typeof ProductsRoute
  PurchasesRoute: typeof PurchasesRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ApiBreefAiRoute: typeof ApiBreefAiRoute
  ApiPurchaseOcrRoute: typeof ApiPurchaseOcrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration': {
      id: '/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof IntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/external-integration': {
      id: '/external-integration'
      path: '/external-integration'
      fullPath: '/external-integration'
      preLoaderRoute: typeof ExternalIntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecommerce': {
      id: '/ecommerce'
      path: '/ecommerce'
      fullPath: '/ecommerce'
      preLoaderRoute: typeof EcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic': {
      id: '/clinic'
      path: '/clinic'
      fullPath: '/clinic'
      preLoaderRoute: typeof ClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/purchase-ocr': {
      id: '/api/purchase-ocr'
      path: '/api/purchase-ocr'
      fullPath: '/api/purchase-ocr'
      preLoaderRoute: typeof ApiPurchaseOcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/breef-ai': {
      id: '/api/breef-ai'
      path: '/api/breef-ai'
      fullPath: '/api/breef-ai'
      preLoaderRoute: typeof ApiBreefAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  ClinicRoute: ClinicRoute,
  DashboardRoute: DashboardRoute,
  DeliveryRoute: DeliveryRoute,
  EcommerceRoute: EcommerceRoute,
  EmployeesRoute: EmployeesRoute,
  ExternalIntegrationRoute: ExternalIntegrationRoute,
  IntegrationRoute: IntegrationRoute,
  InventoryRoute: InventoryRoute,
  MarketingRoute: MarketingRoute,
  MessagesRoute: MessagesRoute,
  PatientsRoute: PatientsRoute,
  ProductsRoute: ProductsRoute,
  PurchasesRoute: PurchasesRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ApiBreefAiRoute: ApiBreefAiRoute,
  ApiPurchaseOcrRoute: ApiPurchaseOcrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
